// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CheckoutItem struct {
	Sku             string  `json:"sku"`
	Name            string  `json:"name"`
	Price           float64 `json:"price"`
	DiscountedPrice float64 `json:"discountedPrice"`
	Quantity        int     `json:"quantity"`
	FreeQuantity    int     `json:"freeQuantity"`
}

type CheckoutResult struct {
	Message    string          `json:"message"`
	TotalPrice float64         `json:"totalPrice"`
	Items      []*CheckoutItem `json:"items"`
}

type ScanItem struct {
	Sku      string `json:"sku"`
	Quantity int    `json:"quantity"`
}

type ScanItems struct {
	Items []*ScanItem `json:"items"`
}

type ScanItemsResult struct {
	Message string `json:"message"`
}
